INSERT INTO map_urbandatadescription (code, name, description) values ('adt_101', 'Average Daily Traffic', 'Average number of daily cars per street');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_101', 'Income', '2014 Per Capita Income');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_102', 'Income', '2014 Per Capita Income');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_103', 'Income', '2014 Per Capita Income');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_104', 'Density', 'Number of male population less than 5 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_105', 'Density', 'Number of male population between 5 and 9 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_106', 'Density', 'Number of male population between 10 and 14 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_107', 'Density', 'Number of male population between 15 and 19 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_108', 'Density', 'Number of male population between 20 and 24 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_109', 'Density', 'Number of male population between 25 and 29 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_110', 'Density', 'Number of male population between 30 and 34 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_111', 'Density', 'Number of male population between 35 and 39 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_112', 'Density', 'Number of male population between 40 and 44 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_113', 'Density', 'Number of male population between 45 and 49 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_114', 'Density', 'Number of male population between 50 and 54 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_115', 'Density', 'Number of male population between 55 and 59 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_116', 'Density', 'Number of male population between 60 and 64 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_117', 'Density', 'Number of male population between 65 and 69 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_118', 'Density', 'Number of male population between 70 and 74 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_119', 'Density', 'Number of male population between 75 and 79 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_120', 'Density', 'Number of male population between 80 and 84 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_121', 'Density', 'Number of male population more than 85 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_122', 'Density', 'Number of male population less than 5 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_123', 'Density', 'Number of female population between 5 and 9 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_124', 'Density', 'Number of female population between 10 and 14 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_125', 'Density', 'Number of female population between 15 and 19 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_126', 'Density', 'Number of female population between 20 and 24 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_127', 'Density', 'Number of female population between 25 and 29 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_128', 'Density', 'Number of female population between 30 and 34 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_129', 'Density', 'Number of female population between 35 and 39 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_130', 'Density', 'Number of female population between 40 and 44 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_131', 'Density', 'Number of female population between 45 and 49 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_132', 'Density', 'Number of female population between 50 and 54 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_133', 'Density', 'Number of female population between 55 and 59 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_134', 'Density', 'Number of female population between 60 and 64 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_135', 'Density', 'Number of female population between 65 and 69 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_136', 'Density', 'Number of female population between 70 and 74 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_137', 'Density', 'Number of female population between 75 and 79 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_138', 'Density', 'Number of female population between 80 and 84 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_139', 'Density', 'Number of female population more than 85 years');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_151', 'Density', 'Number of people by tapestry: Enterprising Professionals 2014');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_152', 'Density', 'Number of people by tapestry: Laptops and Lattes 2014');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_153', 'Density', 'Number of people by tapestry: Trendsetters 2014');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_154', 'Density', 'Number of people by tapestry: Urban Chic 2014');
INSERT INTO map_urbandatadescription (code, name, description) values ('deg_155', 'Density', 'Sum of tapestry (DEN 151 to DEN 154)');
INSERT INTO map_urbandatadescription (code, name, description) values ('poi_101', 'Point of Interest', 'Number of points of interest within 1,000 feet: -bars, caffes, pharmacy, supermarkets, ATM, college, musseums');
INSERT INTO map_urbandatadescription (code, name, description) values ('poi_102', 'Point of Interest', 'Number of atm within 1,000 feet');
INSERT INTO map_urbandatadescription (code, name, description) values ('poi_103', 'Point of Interest', 'Number of bar within 1,000 feet');
INSERT INTO map_urbandatadescription (code, name, description) values ('poi_104', 'Point of Interest', 'Number of coffee within 1,000 feet');
INSERT INTO map_urbandatadescription (code, name, description) values ('poi_105', 'Point of Interest', 'Number of college within 1,000 feet');
INSERT INTO map_urbandatadescription (code, name, description) values ('poi_106', 'Point of Interest', 'Number of museum within 1,000 feet');
INSERT INTO map_urbandatadescription (code, name, description) values ('poi_107', 'Point of Interest', 'Number of pharmacy within 1,000 feet');
INSERT INTO map_urbandatadescription (code, name, description) values ('poi_108', 'Point of Interest', 'Number of grocery/ supermarket within 1,000 feet');
INSERT INTO map_urbandatadescription (code, name, description) values ('poi_109', 'Point of Interest', 'Number of furniture within 1,000 feet');
INSERT INTO map_urbandatadescription (code, name, description) values ('poi_110', 'Point of Interest', 'Number of furniture, groceries, pharmacies');
INSERT INTO map_urbandatadescription (code, name, description) values ('den_101', 'Density', 'Number of residents per square mile');
INSERT INTO map_urbandatadescription (code, name, description) values ('den_102', 'Density', 'Number of employees per square mile');
INSERT INTO map_urbandatadescription (code, name, description) values ('den_103', 'Density', 'Number of residents per square mile');
INSERT INTO map_urbandatadescription (code, name, description) values ('den_104', 'Density', 'Number of residents per square mile');
INSERT INTO map_urbandatadescription (code, name, description) values ('den_105', 'Density', 'Number of employees per square mile');
INSERT INTO map_urbandatadescription (code, name, description) values ('den_106', 'Density', 'Number of employees per square mile');
INSERT INTO map_urbandatadescription (code, name, description) values ('den_150', 'Density', 'Number of target population per square Mile');
INSERT INTO map_urbandatadescription (code, name, description) values ('beh_101', 'Behaviours', 'Spend Index at Full Server Dinner Restaurant (100 = USA average)');
INSERT INTO map_urbandatadescription (code, name, description) values ('beh_102', 'Behaviours', 'Spend Index at Full Server Lunch Restaurant (100 = USA average)');
INSERT INTO map_urbandatadescription (code, name, description) values ('beh_103', 'Behaviours', 'Spend Index at Full Server Dinner Restaurant (100 = USA average)');
INSERT INTO map_urbandatadescription (code, name, description) values ('beh_105', 'Behaviours', 'Spend Index at Full Server Lunch Restaurant (100 = USA average)');
INSERT INTO map_urbandatadescription (code, name, description) values ('beh_108', 'Behaviours', 'Spend Index at Full Server Lunch Restaurant (100 = USA average)');
INSERT INTO map_urbandatadescription (code, name, description) values ('beh_150', 'Behaviours', 'Spend Number (US$) at Beer at Fast Food Restaurant');
INSERT INTO map_urbandatadescription (code, name, description) values ('beh_151', 'Behaviours', 'Spend Average (US$) at Beer at Fast Food Restaurant');
INSERT INTO map_urbandatadescription (code, name, description) values ('beh_152', 'Behaviours', 'Spend Index at Beer at Fast Food Restaurant');
INSERT INTO map_urbandatadescription (code, name, description) values ('gpp_101', 'Point of Interest', 'Number of points of interest within 300 mts: bars, caffes, pharmacy, supermarkets, ATM, college, musseums');
INSERT INTO map_urbandatadescription (code, name, description) values ('atm', 'Point of Interest', 'Number of atm within 300 mts');
INSERT INTO map_urbandatadescription (code, name, description) values ('bar', 'Point of Interest', 'Number of bar within 300 mts');
INSERT INTO map_urbandatadescription (code, name, description) values ('cafe', 'Point of Interest', 'Number of coffee within 300 mts');
INSERT INTO map_urbandatadescription (code, name, description) values ('university', 'Point of Interest', 'Number of college within 300 mts');
INSERT INTO map_urbandatadescription (code, name, description) values ('museum', 'Point of Interest', 'Number of museum within 300 mts');
INSERT INTO map_urbandatadescription (code, name, description) values ('pharmacy', 'Point of Interest', 'Number of pharmacy within 300 mts');
INSERT INTO map_urbandatadescription (code, name, description) values ('grocery_or_supermarket', 'Point of Interest', 'Number of grocery/ supermarket 300 mts');
INSERT INTO map_urbandatadescription (code, name, description) values ('furniture_store', 'Point of Interest', 'Number of furniture within 300 mts');
